{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "Nav_ClienteDetail"
	},
	"PageToOpen": "/Colombina/Pages/clientes/Detalle_Cliente.page",
	"ClearHistory": false,
	"OuterNavigation": true
}