{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "Crear_Visita"
	},
	"OnSuccess": "/Colombina/Rules/clientes/visita_exitosa.js",
	"Target": {
		"Service": "/Colombina/Services/Colombina.service",
		"EntitySet": "Clientes",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"id": "{id}",
		"lat": "Activa"
	}
}