{
	"_Type": "Action.Type.OfflineOData.Download",
	"ActionResult": {
		"_Name": "Download_Pedido"
	},
	"OnSuccess": "/Colombina/Actions/ClosePage.action",
	"Service": "/Colombina/Services/Colombina.service",
	"DefiningRequests": [
		{
			"Name": "Aux_Pedido",
			"Query": "Aux_Pedido",
			"AutomaticallyRetrievesStreams": false
		}
	]
}