{
	"_Type": "Action.Type.ODataService.DeleteEntity",
	"ActionResult": {
		"_Name": "EliminarItem"
	},
	"OnSuccess": "/Colombina/Rules/clientes/ItemPedidos.js",
	"Target": {
		"Service": "/Colombina/Services/Colombina.service",
		"EntitySet": "Aux_Pedido",
		"QueryOptions": "",
		"ReadLink": "{@odata.readLink}"
	}
}