{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "Finalizar_Visita"
	},
	"OnSuccess": "/Colombina/Actions/Service/Update_HISTV.action",
	"Target": {
		"Service": "/Colombina/Services/Colombina.service",
		"EntitySet": "Clientes",
		"QueryOptions": "$filter=lat eq 'Activa'",
		"ReadLink": ""
	},
	"Properties": {
		"lat": "Inactiva"
	}
}