{
	"_Type": "Action.Type.ToastMessage",
	"ActionResult": {
		"_Name": "Msg_anadircarrito"
	},
	"OnSuccess": "/Colombina/Actions/Close_Page_Pedido.action",
	"Message": "Producto añadido al carrito",
	"Duration": 2,
	"Icon": "sap-icon://cart-2"
}