{
	"_Type": "Action.Type.BannerMessage",
	"ActionResult": {
		"_Name": "Msg_pedidoenviado"
	},
	"OnSuccess": "/Colombina/Actions/Nav_home.action",
	"Message": "El pedido fue enviado satisfactoriamente",
	"Duration": 5
}