{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "Msg_pedidoenviado"
	},
	"OnSuccess": "/Colombina/Actions/Nav_home.action",
	"Message": "El pedido fue enviado al sistema",
	"Title": "Exito",
	"OKCaption": "OK",
	"OnOK": "/Colombina/Actions/Nav_home.action"
}