{
    "Animated": true,
    "Duration": 2,
    "Message": "Entity updated",
    "Icon": "",
    "IsIconHidden": false,
    "NumberOfLines": 2,
    "OnSuccess": "/Colombina/Actions/ClosePage.action",
    "_Type": "Action.Type.ToastMessage"
}